# Version of docker-compose
version: '3.7'

# Defines the containers 
services:
  # First project container 
  todoclient:
    # Build parameters for the container
    build: 
      context: .
    ports:
      # Maps ports to be accessed by the app outside of the container
      - "4050:4050"
    volumes:
      # Files that I want to see changes to without rebuilding the container 
      # This is optional, but a useful feature I've had on other projects
      - ./assets/css:/app/assets/css
      - ./assets/js:/app/assets/js
      - ./assets/package.json:/app/assets/package.json
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
      - ./test:/app/test
    depends_on:
      # The `todoclientdb` container needs to be started before `todoclient` is started
      - todoclientdb
    networks:
      - service
      - web
  # Second project container
  todoclientdb:
    # Declares which Postres image to use
    image: postgres:11.5
    # Declare a volume to not loose database data when stopping the container
    volumes:
      - clientpostgres:/var/lib/postgresql/data
    # Maps port to be accessed by `todoclient` container
    ports:
      - "5450:5432"
    networks:
      - service
# This needs to be declared because `volumes` was used in the `todoapidb` and `todoclientdb` container
# Tells Docker to create a volume on the host machine to maintain data
volumes:
  clientpostgres:
networks:
  service:
  web:
    external: true # this means that shared space will be created by the other file
    name: shared-web